version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - logstash
    environment:
      - FLASK_ENV=development
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: heal_db
      MYSQL_USER: heal_user
      MYSQL_PASSWORD: heal_password
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./database_init:/docker-entrypoint-initdb.d  # 초기화 스크립트 경로

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false  # 개발 환경에서는 비활성화, 운영 환경에서는 활성화 권장
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    container_name: logstash
    ports:
      - "5044:5044"  # Logstash Beats input
      - "9600:9600"  # Monitoring API
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    depends_on:
      - elasticsearch
    mem_limit: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_NAME: kibana
      SERVER_HOST: "0.0.0.0"
      xpack.encryptedSavedObjects.encryptionKey: "a_very_long_and_random_string_of_at_least_32_characters"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    mem_limit: 1g


volumes:
  db_data:
  esdata: