version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: heal_db
      MYSQL_USER: heal_user
      MYSQL_PASSWORD: heal_password
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./database_init:/docker-entrypoint-initdb.d  # 초기화 스크립트 경로

volumes:
  db_data: